winget install --accept-source-agreements --accept-package-agreements Google.Chrome
winget install --accept-source-agreements --accept-package-agreements Valve.Steam
winget install --accept-source-agreements --accept-package-agreements Logitech.GHUB
winget install --accept-source-agreements --accept-package-agreements WinDirStat
winget install --accept-source-agreements --accept-package-agreements GitHub.Atom
winget install --accept-source-agreements --accept-package-agreements GitHub.GitHubDesktop
winget install --accept-source-agreements --accept-package-agreements 7zip.7zip
winget install --accept-source-agreements --accept-package-agreements Microsoft.VisualStudioCode
winget install --accept-source-agreements --accept-package-agreements Eugeny.Tabby
winget install --accept-source-agreements --accept-package-agreements 9NBLGGH536CC
winget install --accept-source-agreements --accept-package-agreements CrystalDewWorld.CrystalDiskInfo
winget install --accept-source-agreements --accept-package-agreements Discord.Discord
winget install --accept-source-agreements --accept-package-agreements ALCPU.CoreTemp
winget install --accept-source-agreements --accept-package-agreements VideoLAN.VLC